### ISSUE TITLE
(Not an issue) Respect the API by importing the module only on production builds

### ISSUE THREAD

**Issue by Quiroptero** [lkhrs/hugo-dark-visitors#1]
Opening an issue only because there is no Discussions tab.

---

Hi, Luke, great module!

I suggest a way to Respect the API without relying on Hugo's cache. The idea is to enable the module **only** on production builds. We can make use of the configuration directory, instead of having a standalone configuration file `hugo.yaml`. The [docs](https://gohugo.io/getting-started/configuration/#configuration-directory) provide an example, but for the sake of simplicity let's say we have the following tree:

```
config
├── _default
│   └── hugo.yaml
└── production
    └── hugo.yaml
```

In `_default/hugo.yaml`:

```YAML
module:
  imports:
    - path: "module foo"
    - path: "module bar"
```

In `production/hugo.yaml`:

```YAML
module:
  imports:
    - path: "module foo"
    - path: "module bar"
    - path: "https://github.com/lkhrs/hugo-dark-visitors"
```

From the docs:

> By default, Hugo sets its environment to `development` when running `hugo server`. In the absence of a `config/development` directory, Hugo uses the `config/_default` directory.

> By default, Hugo sets its environment to `production` when running `hugo`.

With this approach we can make endless local builds with `hugo server` without calling the API. When we deploy to production using `hugo` the module will be applied and the API will get a request :slightly_smiling_face:
